# Generated by Django 4.2.4 on 2024-02-14 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('url', models.URLField(unique=True)),
                ('etag', models.CharField(max_length=256, null=True)),
                ('last_modified', models.CharField(max_length=256, null=True)),
                ('last_scan', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('image', models.URLField(blank=True, default='')),
                ('reply_format', models.CharField(default='replying to', max_length=256)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('is_bozo', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('categories', models.ManyToManyField(to='feed.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title_language', models.CharField(blank=True, default='', max_length=50)),
                ('content_language', models.CharField(blank=True, default='', max_length=50)),
                ('categories', models.ManyToManyField(blank=True, to='feed.category')),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feed')),
                ('group_config', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.groupconfig')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='feed.post')),
                ('refer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refer_post', to='feed.post')),
                ('votes_total', models.ManyToManyField(blank=True, related_name='post', to='feed.vote')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='verification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_post', to='feed.post'),
        ),
    ]
