# Generated by Django 4.2.4 on 2023-10-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_voted',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='votes_total',
            field=models.ManyToManyField(related_name='post', to='feed.vote'),
        ),
    ]
