# Generated by Django 4.2.4 on 2023-10-25 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_vote_is_voted_remove_vote_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='last_scan',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
