# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^migrations/

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^migrations/

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.32.0
    hooks:
      - id: djlint-reformat-django
        args: [--reformat]
      - id: djlint-django

        # - repo: https://github.com/pre-commit/mirrors-prettier
        #   rev: 'v2.1.2'
        #   hooks:
        #   -   id: prettier
        #       files: 'bhread/feed/templates/'
        #       additional_dependencies:
        #       -   'prettier-plugin-tailwindcss@0.4.1'
        #
        #
