version: '2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  db:
    image: postgres
      # volumes:
      #   - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # Test if pg is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  tailwind:
    build: .
    volumes:
      - .:/code
    command: python /code/bhread/manage.py tailwind start
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true
  djangoq:
      build: .
      network_mode: "host"
      command: python /code/bhread/manage.py qcluster
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - .:/code
      depends_on:
        - redis
  web:
      build: .
      # Allow access of ports in the host machine (for Test feeds):
      network_mode: "host"
      ports:
        - "8000:8000"
      command: >
        sh -c "python /code/bhread/manage.py migrate
        && python /code/bhread/manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      depends_on:
        db:
          condition: service_healthy
