version: '2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  db:
    image: postgres
      # volumes:
      #   - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # Test if pg is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
      &web
      build: .
      # Allow access of ports in the host machine (for Test feeds):
      network_mode: "host"
      restart: unless-stopped
      ports:
        - "8000:8000"
      command: >
        sh -c "python /code/bhread/manage.py makemigrations \
        && python /code/bhread/manage.py migrate \
        && python /code/bhread/manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - GITHUB_AUTH_CLIENT_ID=/run/secrets/github_auth_client_id
        - GITHUB_AUTH_SECRET=/run/secrets/github_auth_secret
        - GOOGLE_AUTH_CLIENT_ID=/run/secrets/google_auth_client_id
        - GOOGLE_AUTH_SECRET=/run/secrets/google_auth_secret
      depends_on:
        db:
          condition: service_healthy
      secrets:
        - github_auth_secret
        - github_auth_client_id
        - google_auth_secret
        - google_auth_client_id
  tailwind:
      <<: *web
      command: python /code/bhread/manage.py tailwind start
      # Without tty, no stdin, and tailwind watcher aborts
      # https://github.com/tailwindlabs/tailwindcss/issues/5324
      tty: true
  djangoq:
      <<: *web
      command: python /code/bhread/manage.py qcluster

secrets:
  # Initial installation: you need to create the files and put content
  # github: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app
  # google: ?
  github_auth_secret:
    file: secrets/github_auth_secret.txt
  github_auth_client_id:
    file: secrets/github_auth_client_id.txt
  google_auth_secret:
    file: secrets/google_auth_secret.txt
  google_auth_client_id:
    file: secrets/google_auth_client_id.txt
